apiVersion: rollouts.platform.io/v1alpha1
kind: RolloutTemplate
metadata:
  name: argo-demo
  namespace: rollout-system
spec:
  image: argoproj/rollouts-demo:blue
  port: 8080
  replicas: 2
  strategy:
    type: Canary
    canary:
      steps:
      - setWeight: 50
      - pause:
          duration: 30
      - setWeight: 100
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m
