apiVersion: rollouts.platform.io/v1alpha1
kind: RolloutTemplate
metadata:
  name: nginx-nonroot
  namespace: rollout-system
spec:
  image: nginxinc/nginx-unprivileged:alpine
  port: 8080
  replicas: 2
  strategy:
    type: Canary
    canary:
      steps:
      - setWeight: 50
      - pause:
          duration: 30
      - setWeight: 100
  resources:
    requests:
      memory: 32Mi
      cpu: 25m
    limits:
      memory: 64Mi
      cpu: 50m
  securityContext:
    runAsUser: 101
    runAsGroup: 101
    runAsNonRoot: true
