apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-rollouts
  namespace: argo-rollouts
  labels:
    release: grafana-stack
spec:
  namespaceSelector:
    matchNames:
    - argo-rollouts
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts-metrics
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
