apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireArgoRollout
metadata:
  name: enforce-argo-rollout
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaceSelector:
      matchLabels:
        app.kubernetes.io/managed-by: teams-operator
