apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: falcosidekick
  namespace: falco-system
  labels:
    release: grafana-stack  # must match Prometheus serviceMonitorSelector
spec:
  namespaceSelector:
    matchNames:
    - falco-system
  selector:
    matchLabels:
      app.kubernetes.io/name: falcosidekick
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
